### ISSUE TITLE
The path to Rocket.toml is not relative![]

### ISSUE THREAD

**Issue by buranovite** [rwf2/Rocket#2611]
**Existing Functionality**

Right now, as far as I can tell, rocket's default config provider tries to find a `"Rocket.toml"` file (see `Config::figment()` implementation). However, does everybody store the binary in the same folder as Rocket.toml (some might put it in `/usr/local/bin`, for example)?

It would be nice if rocket used the `relative!` macro to find Rocket.toml, that way it's an absolute path, guaranteed to work if you build it on the same machine that you run it on.

**Suggested Changes**

Right now [we have the following lines](https://docs.rs/rocket/0.5.0-rc.3/src/rocket/config/config.rs.html#258):

```rust
Figment::from(Config::default())
  .merge(Toml::file(Env::var_or("ROCKET_CONFIG", "Rocket.toml")).nested())
  // ...
```

that can be replaced by something similar to:
```rust
Figment::from(Config::default())
  .merge(Toml::file(Env::var_or("ROCKET_CONFIG", relative!("Rocket.toml"))).nested())
  // ...
```

**Alternatives Considered**

1. Using the environment variable with a full path to it. Clumsy, users have to remember to update the variable every time they move their project to another location on disk
2. Implementing the merge manually. Rocket promises to be boilerplate-free on its website, why should users have to do this? Is there some hidden and undocumented reason as to why this is the default behavior?

**Additional Context**

None

**Comment by SergioBenitez** [comment]
You can also simply set the `ROCKET_CONFIG` environment variable to the file's path.

**Comment by buranovite** [comment]
> You can also simply set the ROCKET_CONFIG environment variable to the file's path.

I have mentioned that in `Alternatives Considered`:
> Using the environment variable with a full path to it. Clumsy, users have to remember to update the variable every time they move their project to another location on disk

If it was `relative![]` by default, then even relocating the project directory to another disk would be effortless. However, right now users have to remember to update their ENV configs as well

**Comment by SergioBenitez** [comment]
`relative!` resolves a path to the crate root of the project that invokes it. If we invoke it in Rocket itself, it resolves to Rocket's crate root, not the project depending on Rocket. I don't believe there's any way for Rocket to determine the crate root of the top-level crate that depended on it. 

Even if it could, I don't think this makes too much sense. (In fact, I've been thinking of getting rid of the `relative!` macro entirely.) If you move the binary to a different machine, the crate root is extremely unlikely to exist, and now the absolute path is meaningless. The only thing you can do is move the binary along with the file. The current way is to literally do that. An alternative might be to store the file's contents in the binary so that the binary contains the file, and it's automatically bundled. That would solve both your issue and the issue I have with `relative!`.

There are drawbacks here too, however. Should Rocket continue to use a Rocket.toml file it discovers if it has one compiled in? Does that file get merged in, or does it replace the compiled-in config entirely? What is the effect of the ROCKET_CONFIG environment variable, at compile-time? At runtime?

**Comment by fosterushka** [comment]
> `relative!` resolves a path to the crate root of the project that invokes it. If we invoke it in Rocket itself, it resolves to Rocket's crate root, not the project depending on Rocket. I don't believe there's any way for Rocket to determine the crate root of the top-level crate that depended on it.
> 
> Even if it could, I don't think this makes too much sense. (In fact, I've been thinking of getting rid of the `relative!` macro entirely.) If you move the binary to a different machine, the crate root is extremely unlikely to exist, and now the absolute path is meaningless. The only thing you can do is move the binary along with the file. The current way is to literally do that. An alternative might be to store the file's contents in the binary so that the binary contains the file, and it's automatically bundled. That would solve both your issue and the issue I have with `relative!`.
> 
> There are drawbacks here too, however. Should Rocket continue to use a Rocket.toml file it discovers if it has one compiled in? Does that file get merged in, or does it replace the compiled-in config entirely? What is the effect of the ROCKET_CONFIG environment variable, at compile-time? At runtime?
I got the same problem.
So for the use of a Rocket.toml file, Rocket will use the compiled-in configuration if it exists?
What if a Rocket.toml file is also present at runtime, Rocket will merge the two configurations ?
 If it can turns out ROCKET_CONFIG environment variable can be used to override both the compiled-in and runtime configurations.

**Comment by SergioBenitez** [comment]
> So for the use of a Rocket.toml file, Rocket will use the compiled-in configuration if it exists?

This feature doesn't exist at the moment. I'm not sure if it should at all.

In any case, implementing this yourself is rather straightforward:


```rust
use rocket::figment::providers::{Format, Toml};

let figment = Figment::from(rocket::Config::default())
    .merge(Toml::string(include_str!("Rocket.toml")).nested())
    .merge(Env::prefixed("ROCKET_").ignore(&["PROFILE"]).global())
    .select(Profile::from_env_or("ROCKET_PROFILE", rocket::Config::DEFAULT_PROFILE));

rocket::from(figment)
    .mount(..)
    // ...
    .launch()
```

Given it's so easy and there's no "obvious" thing to do Rocket-side, I'm closing this out.
