### ISSUE TITLE
Force enable color output

### ISSUE THREAD

**Issue by levkk** [rwf2/Rocket#2649]
**Is your feature request motivated by a concrete problem? Please describe.**

When running Rocket in local development under an orchestrator like Foreman (together with other apps), the color output gets disabled because subprocesses spawned by Foreman are not real shells (no TTY). The colored output is still desired (it looks nice and helps readability), so we would like to enable it and bypass the TTY check.

**Why this feature can't or shouldn't live outside of Rocket**

Rocket controls its color output. Faking a TTY in Foreman and friends is not obvious, e.g. requires using a fake shell like `tty` in [Python](https://stackoverflow.com/questions/56835373/python-subprocess-realtime-print-with-colors-and-save-stdout). 

**Ideal Solution**

Make `cli_colors` an `Option<bool>`. If specified, `true` will always enable color output, `false` will always disable it, and `None` will default to `true` and the current TTY check.

**Alternatives Considered**

Patching Foreman/Honcho to support color output, but this quickly became a game of cat and mouse with TTY. Can't patch every single subprocess spawner out there, and this issue is not exclusive to Foreman.

**Additional Context**

Happy to contribute a PR, although I'm a bit lost in the Deserializer implementation in Figment for `Option<bool>`. Currently Figment tests aren't compiling in `master`, so a bit of a lift to get started.

**Comment by SergioBenitez** [comment]
> Happy to contribute a PR, although I'm a bit lost in the Deserializer implementation in Figment for `Option<bool>`.

You should assume that it does the right thing. I don't think there's any interesting consideration with Figment.

> Currently Figment tests aren't compiling in `master`, so a bit of a lift to get started.

They are, as you can see with the CI. You just need to compile with all features enabled: `cargo test --all-features`.

**Comment by SergioBenitez** [comment]
As for the actual request, I think this is a good idea. However, I think we should follow a more explicit route, akin to what tools normally do. In particular, changing the color settings to parse `always`, `auto`, and `never` as their name suggests. Internally we can use an `Option<bool>` or an enum - I'd be fine with either, though perhaps an enum would be more self-descriptive. And finally, we'd ideally continue to support the options as before with the same functionality as before, so that this is a backwards compatible change.
