### ISSUE TITLE
cookie removal and Microsoft Edge

### ISSUE THREAD

**Issue by HaHa421** [rwf2/Rocket#2727]
### Rocket Version

0.5.0

### Operating System

windows 10/11

### Rust Toolchain Version

rustc 1.76

### What happened?

using Edge, removing a cookie sets its expiration date not in the past but far in the future : here I get Sunday, September 20, 5838270 
I tested the site using Brave, Firefox end Chrome : the cookie is cleared as expected 

### Test Case

```rust
//
```

### Log Output

```shell
//
```

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by SergioBenitez** [comment]
Please provide a test case and a screenshot of the browser as well as the exact version of the browser.

**Comment by SergioBenitez** [comment]
I'm sorry, but you're going to need to provide clearer information about what's going on. I have tried to reproduce the issue you're describing without success. On both macOS and Windows, Edge successfully clears the cookie.

Here's what I need from you:

  * A console log of Rocket with your reproduction showing incoming and outgoing requests where the issue occurs with debug logging enabled. This was requested in the issue template but was ignored.
  * A screenshot of the developer tools in your Edge browser that shows the information you're describing here. When a cookie is deleted, both `max-age` and `Expires` are set. I need to see what the browser is receiving, exactly. Ideally, this is two things: the response headers and the cookie information. 

Please also format your responses with markdown so that they're easier to read.

Please do not ignore issue templates in the future. They are designed so that this back-and-forth is avoided as much as possible. When you ignore the issue template, you increase workload on maintainers unnecessarily.

**Comment by HaHa421** [comment]
I' m afraid the formatting will be horrible but rocket log writes as expected:
 sending response: Response {
    status: 200,
    version: HTTP/1.1,
    headers: {
        "set-cookie": "test_cookie=; SameSite=Lax; Path=/; Max-Age=0; Expires=Thu, 16 Feb 2023 01:41:49 GMT",
        "server": "Rocket",
        "x-content-type-options": "nosniff",
        "x-frame-options": "SAMEORIGIN",
        "permissions-policy": "interest-cohort=()",
        "content-length": "0",
    },
    body: Body(
        Streaming,
    ),
}
and I get only this warning in Edge developer tools console:
````
Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.
````
Edge keeps writing an expiration date : Sunday, September 20, 5838270 at 12:09:20 AM which didn't change btw

**Comment by HaHa421** [comment]
I get the same behavior from Edge on a linux machine

**Comment by SergioBenitez** [comment]
Please post the following:

> I need to see what the browser is receiving, exactly. Ideally, this is two things: the response headers and the cookie information.

This can be found in the developer tools.

**Comment by HaHa421** [comment]
When an inspect cookies in the Application tab of developer tools, the cookie doesn't show after removal which is good 
I added the route 
````
#[get("/check_cookie")]
async fn check_cookie(cookies: &CookieJar<'_>)->String {
    match cookies.get("test_cookie") {
      Some(_)=>String::from("Cookie found"),
      _=>String::from("Cookie not found"),
    }
}
````
and everything is ok
Meanwhile the cookie still shows up in the "View Site Information --> Cookies" ,which might be annoying from a user perspective. 
anyway , this seems to be related to Edge implementation so I suppose we can close the issue
