### ISSUE TITLE
Deployment Docs - Static Files

### ISSUE THREAD

**Issue by elibroftw** [rwf2/Rocket#2796]
### What kind of documentation problem are you reporting?

Technical Problem

### Where is the issue found?

https://rocket.rs/guide/v0.5/deploying/

### What's wrong?

Since we are using a reverse proxy already, the docs do not mention whether rocket's static file serving will be superior than letting the reverse proxy handle it.

Additionally, for deploying gunicorn/wsgi apps, we use unix sockets. Is http proxy pass really the modern way to do this?

`proxy_pass http://unix:$project_dir/gunicorn.sock;`

Also you don't need to set proxy headers explictly, `include proxy_params;` takes car of this

### System Checks

- [X] I confirmed that the issue still exists on `master` on GitHub.
- [X] I was unable to find a previous report of this problem.

**Comment by SergioBenitez** [comment]
The guide cannot possibly enumerate all possible deployment options, so it suggests a few (good) ways to do things. We're happy to address any specific concerns with deploying, such as the ones you've asked here, but ideally the guide itself stays as general as possible. For any such questions, it's best to use [discussions](https://github.com/rwf2/Rocket/discussions).

> Since we are using a reverse proxy already, the docs do not mention whether rocket's static file serving will be superior than letting the reverse proxy handle it.

Letting the reverse proxy serve static files may be just as good, or better, than letting Rocket handle it. For example, NGINX can use `sendfile` on Linux to serve static files, which is more efficient than what Rocket does. It really depends on whether the reverse proxy provides all the functionality you need with its static file serving, and whether you want to have two places where your application is configured. But it's fine to do either. 

> Additionally, for deploying gunicorn/wsgi apps, we use unix sockets. Is http proxy pass really the modern way to do this?

Either is fine, though using unix domain sockets is likely the preferred approach because 1) it _can_ be slightly more efficient, and 2) it _can_ be easier to secure a unix domain socket. Rocket v0.5 doesn't support serving over unix domain sockets, but Rocket v0.6 will (and master already does), so we should definitely update the guide with this option in mind.

> Also you don't need to set proxy headers explictly, `include proxy_params;` takes car of this

Is the `proxy_params` file _guaranteed_ to ship with all modern versions of NGINX on all recent distributions? There are certainly reports online that indicate no. We want the guide to work with all recent distributions.
