### ISSUE TITLE
TextStream not being dropped when client disconnects

### ISSUE THREAD

**Issue by kvinwang** [rwf2/Rocket#2888]
### Rocket Version

master@3bf9ef02d6e803fe9f753777f5a829dda6d2453d

### Operating System

Ubuntu 24.04

### Rust Toolchain Version

rustc 1.80.0

### What happened?

I'm implementing a log streaming feature similar to `tail -f` using the `TextStream!` macro. The stream continues running even after the client disconnects, which may lead to resource leaks.

### Test Case

```rust
use rocket::{get, launch, routes};
use rocket::response::stream::TextStream;

#[get("/")]
fn test() -> TextStream![&'static str] {
    struct Guard;
    impl Drop for Guard {
        fn drop(&mut self) {
            println!("Stream dropped");
        }
    }
    TextStream! {
        let _guard = Guard;
        yield "test\n";
        loop {
            println!("running...");
            tokio::time::sleep(std::time::Duration::from_millis(100)).await;
        }
    }
}

#[launch]
fn rocket() -> _ {
    rocket::build().mount("/", routes![test])
}
```

### Log Output

```shell
running...
running...
running...
running...
running...
running...
running...
```

## Current Behavior
When a client makes a `GET /test` request and then disconnects, the stream continues to run and prints "running..." to the console indefinitely. The `Guard`'s drop implementation is never called.

## Expected Behavior
Ideally, the stream should be dropped and cleaned up when the client disconnects. Alternatively, there should be a way to detect when the client has disconnected so the stream can be manually aborted.

## Additional information
If it yields new content, the stream will abort due to broken pipe error. However, this is not sufficient for my use case because the tail-follow feature doesn't always produce new content.

```rust
#[get("/test")]
fn test() -> TextStream![String] {
    TextStream! {
        let mut tail = tailf("app.log");
        while let Some(line) = tail.next_line().await {
            // The log file may be inactive for days without new entries
            yield line;
        }
    }
}
```

## Questions
1. Is there a recommended way to detect client disconnection? Maybe, someting like:

```rust
    loop {
        tokio::select! {
            // Check if client disconnected
            _ = client_disconnected() => {
                break;
            }
            // Try to read next line
            maybe_line = tail.next_line() => {
                if let Some(line) = maybe_line {
                    yield line;
                }
            }
        }
    }
```

2. If this is a bug, what would be the best approach to fix it?

### System Checks

- [X] My bug report relates to functionality.
- [X] I have tested against the latest Rocket release or a recent git commit.
- [X] I have tested against the latest stable `rustc` toolchain.
- [X] I was unable to find this issue previously reported.

**Comment by the10thWiz** [comment]
Doing some quick testing, it looks like if you try and send data, it will end the connection (and print the stream end message). One simple solution would be to continually try to send data on the connection. From other projects I have worked on, the OS (on both the client and server) adds a timeout to the TCP connection, so if you don't continue to send data, it will simply close the connection. To avoid this, you likely need to send some bytes every couple seconds, even if you don't have any new lines to send. Depending on what your use case and client look like, these heartbeat messages may take a variety of forms, but you usually want to ensure they are small, and easy to identify.

As far as fixing the underlying issue you found - I don't know if there's much we can do. As far as I can tell, the stream will be dropped as soon as the connection returns an `Err` result, but it can't do that if we don't provide it any data to try sending. In principle, it might be possible to implement if we tried to call flush (since it's also a point the OS can report the disconnect), but this is actually handled by Hyper under the hood right now, so we don't have the ability to fix this. It's also not clear whether this would be desirable behavior in general - I don't think we want to require every handler to be cancel-safe.
